name: dota-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.11
  - pip

  # Data
  - pandas
  - numpy
  - requests

  # Visualization & Dashboard
  - matplotlib
  - seaborn
  - streamlit

  # Jupyter / Notebooks
  - jupyter
  - jupyterlab
  - ipykernel

  # ML / Stats (optional, for pick/ban modeling later)
  - scikit-learn
  - statsmodels

  # Pip installs
  - pip:
      - streamlit-option-menu   # optional UI enhancement
      - plotly                  # interactive charts